/* generated by tools/convert.py - do not edit */
#ifndef DATA_H
#define DATA_H
#define FIELD_CH_COLS 16
#define FIELD_CH_ROWS 13
#define BLANK_PIXEL 136
#define N_FIELD_TILES 208
#define N_TILE_TOTAL 224
extern const unsigned char palette_rgb[256][3];
#define COL_INK 136
#define COL_RIM 215
/* the font: 41 glyphs of 4x6 pixels, one bit per pixel (row by row, low bit first), in two colour sets */
extern const unsigned char font_bits[41][3];
#define FONT_FG0 55
#define FONT_FG1 63
extern const unsigned char life_px[48];
#endif
