/* generated by tools/convert.py - do not edit */
#ifndef SPRITES_H
#define SPRITES_H
/* a sprite is w x h bytes (a GameTank palette index each, 0 = transparent) at offset off in the block that the
 * SPRITES file puts in chip RAM at $10000 */
typedef struct { unsigned char w, h; unsigned int off; } SoftSprite;
#define SPRITE_BLOCK_SIZE 8368
#define GLYPH_OFF 6400       /* glyph images: set * 41 + index, 24 bytes each */
#define SPR_BAT0 0
#define SPR_BAT1 1
#define SPR_BURST0 2
#define SPR_BURST1 3
#define SPR_BURST2 4
#define SPR_BURST3 5
#define SPR_DOUG_0_0 6
#define SPR_DOUG_0_1 7
#define SPR_DOUG_1_0 8
#define SPR_DOUG_1_1 9
#define SPR_DOUG_2_0 10
#define SPR_DOUG_2_1 11
#define SPR_DOUG_3_0 12
#define SPR_DOUG_3_1 13
#define SPR_DOUG_X0 14
#define SPR_DOUG_X1 15
#define SPR_EMB_0_0 16
#define SPR_EMB_0_1 17
#define SPR_EMB_1_0 18
#define SPR_EMB_1_1 19
#define SPR_FLAME0 20
#define SPR_FLAME1 21
#define SPR_GHOST0 22
#define SPR_GHOST1 23
#define SPR_GK_0_0 24
#define SPR_GK_0_1 25
#define SPR_GK_1_0 26
#define SPR_GK_1_1 27
#define SPR_GRUB_0_0 28
#define SPR_GRUB_0_1 29
#define SPR_GRUB_1_0 30
#define SPR_GRUB_1_1 31
#define SPR_LIFE 32
#define SPR_MARK_X17 33
#define SPR_MARK_X263 34
#define SPR_MARK_X27 35
#define SPR_MARK_X363 36
#define SPR_MARK_X391 37
#define SPR_MARK_X463 38
#define SPR_MARK_X591 39
#define SPR_MARK_X691 40
#define SPR_ROCK 41
#define SPR_ROCKC0 42
#define SPR_ROCKC1 43
#define SPR_ROCKW0 44
#define SPR_ROCKW1 45
#define SPR_TOMB 46
#define SPR_MASCOT_0_0 47
#define SPR_MASCOT_0_1 48
#define SPR_MASCOT_1_0 49
#define SPR_MASCOT_1_1 50
#define SPR_MASCOTINF0 51
#define SPR_MASCOTINF1 52
#define SPR_MASCOTINF2 53
#define SPR_MASCOTINF3 54
#define N_SOFT_SPRITES 55
extern const SoftSprite soft_sprites[N_SOFT_SPRITES];
#endif
