/* generated by tools/convert.py - do not edit */
#ifndef SPRITES_H
#define SPRITES_H
/* pixels are 4 bits each (high nybble first, 0 = transparent); pal maps a nybble to a GameTank palette index */
typedef struct { unsigned char w, h; const unsigned char *px; const unsigned char *pal; } SoftSprite;
#define SPR_BAT0 0
#define SPR_BAT1 1
#define SPR_BURST0 2
#define SPR_BURST1 3
#define SPR_BURST2 4
#define SPR_BURST3 5
#define SPR_EMB_0_0 6
#define SPR_EMB_0_1 7
#define SPR_EMB_1_0 8
#define SPR_EMB_1_1 9
#define SPR_FLAME0 10
#define SPR_FLAME1 11
#define SPR_GHOST0 12
#define SPR_GHOST1 13
#define SPR_GK_0_0 14
#define SPR_GK_0_1 15
#define SPR_GK_1_0 16
#define SPR_GK_1_1 17
#define SPR_GRUB_0_0 18
#define SPR_GRUB_0_1 19
#define SPR_GRUB_1_0 20
#define SPR_GRUB_1_1 21
#define SPR_LIFE 22
#define SPR_MARK_X17 23
#define SPR_MARK_X263 24
#define SPR_MARK_X27 25
#define SPR_MARK_X363 26
#define SPR_MARK_X391 27
#define SPR_MARK_X463 28
#define SPR_MARK_X591 29
#define SPR_MARK_X691 30
#define SPR_ROCK 31
#define SPR_ROCKC0 32
#define SPR_ROCKC1 33
#define SPR_ROCKW0 34
#define SPR_ROCKW1 35
#define SPR_TOMB 36
#define SPR_MASCOT_0_0 37
#define SPR_MASCOT_0_1 38
#define SPR_MASCOT_1_0 39
#define SPR_MASCOT_1_1 40
#define SPR_MASCOTINF0 41
#define SPR_MASCOTINF1 42
#define SPR_MASCOTINF2 43
#define SPR_MASCOTINF3 44
#define N_SOFT_SPRITES 45
extern const SoftSprite soft_sprites[N_SOFT_SPRITES];
#endif
